{
  "hash": "3a52e4de5396974f659448e859f803cb",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Comparing Quantitative Data and Sampling\"\nsubtitle: \"Linking Probability and Data\"  \nauthor: \"Robert  W. Walker\"\ndate: '2026-03-17'\nformat: \n   revealjs:\n     theme: [custom.scss]\n     scrollable: true\n     logo: AGSMlogo.jpeg\n     footer: \"BUS 1301-SP26\"\n     multiplex:\n       url: 'https://multiplex-5adl.onrender.com'\n     html-math-method: katex\n     incremental: true\n     slide-number: c/t\n     transition: zoom\n     preview-links: true\n     lightbox: true\n---\n\n\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(url(\"https://github.com/robertwwalker/DADMStuff/raw/master/Big-Week-6-RSpace.RData\"))\n```\n:::\n\n\n\n\n## Paired t-test\n\n### Twinsberg\n\nThe paired t-test is a single sample average applied to the measured difference.  The key is knowing who is matched with whom and believing that there is at least some variation in both outcomes that depends on the unit in question.  \n\nThere is a linguistic distinction; this is an average difference instead of the previous difference in averages.  The language describes the order of operation.  For the paired comparison, I must know what to subtract from what.\n\nTake the example of *Concrete*.\n\n---\n\nTwelve distinct batches of concrete are subjected to an additive.  Does the additive strengthen concrete?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nConcrete %>% datatable()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-db0920666633c03c7e71\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-db0920666633c03c7e71\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"data\":[[\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\"],[1,2,3,4,5,6,7,8,9,10,11,12],[4550,4950,6250,5700,5350,5300,5150,5800,4900,6050,5550,5750],[4600,4900,6650,5950,5700,5400,5400,5850,4850,6450,5850,5600],[-50,50,-400,-250,-350,-100,-250,-50,50,-400,-300,150]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th> <\\/th>\\n      <th>Batch<\\/th>\\n      <th>No.Add<\\/th>\\n      <th>Additive<\\/th>\\n      <th>Diff<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"columnDefs\":[{\"className\":\"dt-right\",\"targets\":[1,2,3,4]},{\"orderable\":false,\"targets\":0},{\"name\":\" \",\"targets\":0},{\"name\":\"Batch\",\"targets\":1},{\"name\":\"No.Add\",\"targets\":2},{\"name\":\"Additive\",\"targets\":3},{\"name\":\"Diff\",\"targets\":4}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n\n## The Average Difference\n\nFor each batch, we can calculate the difference between those with and without an additive.  To do so, we need *mutate*.  Let's plot it.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ResampleProps)\nConcrete <- Concrete %>% mutate(Difference = Additive - No.Add)\nhist(Concrete$Difference)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-3-1.svg){width=624}\n:::\n:::\n\n\n## Resampling\n\n\n::: {.cell}\n\n```{.r .cell-code}\nConcrete.Diff <- data.frame(Sampled.Mean.Difference = ResampleMean(Concrete$Difference))\nquantile(Concrete.Diff$Sampled.Mean.Difference, probs=c(0.025, 0.975))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     2.5%     97.5% \n 54.16667 254.16667 \n```\n\n\n:::\n:::\n\n\n## Graphic\n\n\n::: {.cell}\n\n```{.r .cell-code}\nConcrete.Diff %>% ggplot() + aes(x=Sampled.Mean.Difference) + geom_density() + theme_ipsum_rc()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-5-1.svg){width=624}\n:::\n:::\n\n\n## t-test\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(Concrete$Difference)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  Concrete$Difference\nt = 2.8793, df = 11, p-value = 0.01499\nalternative hypothesis: true mean is not equal to 0\n95 percent confidence interval:\n  37.29936 279.36730\nsample estimates:\nmean of x \n 158.3333 \n```\n\n\n:::\n:::\n\n\nWith 95% confidence, the additive increases the average break-weight of the concrete by 37.3 to 279.4 pounds.\n\n## Is this what Marketing Wants?\n\nProbably not.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(Concrete$Difference, alt=\"greater\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  Concrete$Difference\nt = 2.8793, df = 11, p-value = 0.007495\nalternative hypothesis: true mean is greater than 0\n95 percent confidence interval:\n 59.57616      Inf\nsample estimates:\nmean of x \n 158.3333 \n```\n\n\n:::\n:::\n\n\n**In 90 percent of your applications, additive concrete is 60 units stronger.**\n\n# An Inference Map\n\nWith proportions: If we claim a value of $\\pi$, then use it for the standard error.  If not, use the data.\n\nWith quantities: If comparing them, are samples independent or dependent?  All the relevant quantities are known [or assumed] functions of the data.\n\nFor differences, the `magic number` is nearly always zero -- no difference.\n\n## Code Summary {.smaller}\n\n:::: {.columns}\n::: {.column width=\"50%\"}\n\n### Discrete\n\nFor one proportion:\n\n- `ResampleProps::ResampleProp(vec.data, k=1000, tab.col=1)`\n- `binom.test(x, n, alternative=\"?\", p=0.5, conf.level=0.95)`\n- `prop.test(x, n, alternative=\"?\", p=0.5, conf.level=0.95, correct=TRUE)`\n\nFor two proportions:\n\n- `prop.test(x=c(10,20), n=c(50, 50), alternative=\"?\", p=0.5, conf.level=0.95, correct=TRUE)`\n\n:::\n::: {.column width=\"50%\"}\n\n### Quantities\n\nFor one mean:\n\n- `ResampleMeans::ResampleMean(vec.data, k=1000)`\n- `t.test(x, alternative=\"?\", mu=0, conf.level=0.95)`\n\nFor two means:\n\n- `ResampleDiffMeans(vec.1, vec.2, k=1000)`\n\n- Two types:\n   + Independent: `t.test(x, y, alternative=\"?\", mu=0, conf.level=0.95, paired=FALSE, var.equal=FALSE)`\n   + Paired: `t.test(x, y, alternative=\"?\", mu=0, conf.level=0.95, paired=TRUE)`\n\n:::\n::::\n\n```\n\n\n\n# A Workflow\n\n1. Do we want an hypothesis test or a confidence interval?\n\n2. Choose a level of confidence/significance/probability.\n\n3. If hypothesis test, derive the relevant critical value by combining the reference distribution with the level of confidence/significance/probability.  What value of $z$ or $t$ would be required to reject the hypothesis?  If an confidence interval, how many standard errors from the mean are covered by the given level of probability.\n\n4. If an hypothesis test, calculate the test statistic.\n\n5. Compute the confidence interval or compare the test statistic to the relevant critical value.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<link href=\"../../site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/datatables-binding-0.34.0/datatables.js\"></script>\n<script src=\"../../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}