{
  "hash": "d9def2cbe52625e9717062add4c1b60c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Probability Distributions and Inference\"\nsubtitle: \"Linking Probability and Data\"  \nauthor: \"Robert  W. Walker\"\ndate: '2026-03-17'\nformat: \n   revealjs:\n     theme: [custom.scss]\n     scrollable: true\n     logo: AGSMlogo.jpeg\n     footer: \"BUS 1301-SP26\"\n     multiplex:\n       url: 'https://multiplex-5adl.onrender.com'\n     html-math-method: katex\n     incremental: true\n     slide-number: c/t\n     transition: zoom\n     preview-links: true\n     lightbox: true\n---\n\n\n\n\n\n# Bernoulli Trials\n\n## The Generic Bernoulli Trial\n\nSuppose the variable of interest is discrete and takes only two values: yes and no.  For example, is a customer satisfied with the outcomes of a given service visit?  \n\nFor each individual, because the probability of yes (1) $\\pi$ and no (0) 1-$\\pi$ must sum to one, we can write:\n\n$$f(x|\\pi) = \\pi^{x}(1-\\pi)^{1-x}$$\n\n\n# Binomial Distribution\n\nFor multiple identical trials, we have the Binomial:\n\n$$f(x|n,\\pi) = {n \\choose k} \\pi^{x}(1-\\pi)^{n-x}$$\nwhere $${n \\choose k} = \\frac{n!}{(n-k)!k!}$$\n\n\n## Scottish Pounds\n\n*Informal surveys suggest that 15% of Essex shopkeepers will not accept Scottish pounds.  There are approximately 200 shops in the general High Street square.*\n\n1. Draw a plot of the distribution of shopkeepers that do not accept Scottish pounds.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nScots <- data.frame(Potential.Refusers = 0:200) %>% mutate(Prob = round(pbinom(Potential.Refusers, size=200, 0.15), digits=4))\nScots %>% ggplot() + aes(x=Potential.Refusers, y=Prob) + geom_point() + labs(x=\"Refusers\", y=\"Prob. of x or Less Refusers\") + theme_minimal() -> Plot1\nPlot1\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-1-1.svg){width=624}\n:::\n:::\n\n\n\n## A Nicer Plot\n\n:::: {.columns}\n::: {.column width=\"40%\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(plotly)\np <- ggplotly(Plot1)\np\n```\n:::\n\n\n:::\n::: {.column width=\"60%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"plotly html-widget html-fill-item\" id=\"htmlwidget-c6e0b1269a30204f132a\" style=\"width:624px;height:576px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-c6e0b1269a30204f132a\">{\"x\":{\"data\":[{\"x\":[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200],\"y\":[0,0,0,0,0,0,0,0,0,0,0,0,0.0001,0.00020000000000000001,0.00040000000000000002,0.001,0.0020999999999999999,0.0043,0.0082000000000000007,0.0149,0.025499999999999998,0.041500000000000002,0.064500000000000002,0.095899999999999999,0.1368,0.18759999999999999,0.248,0.31659999999999999,0.39140000000000003,0.46970000000000001,0.54849999999999999,0.62470000000000003,0.69579999999999997,0.75960000000000005,0.81499999999999995,0.86129999999999995,0.89870000000000005,0.92800000000000005,0.95020000000000004,0.96650000000000003,0.97799999999999998,0.98599999999999999,0.99129999999999996,0.99470000000000003,0.99690000000000001,0.99819999999999998,0.999,0.99950000000000006,0.99970000000000003,0.99980000000000002,0.99990000000000001,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],\"text\":[\"Potential.Refusers:   0<br />Prob: 0.0000\",\"Potential.Refusers:   1<br />Prob: 0.0000\",\"Potential.Refusers:   2<br />Prob: 0.0000\",\"Potential.Refusers:   3<br />Prob: 0.0000\",\"Potential.Refusers:   4<br />Prob: 0.0000\",\"Potential.Refusers:   5<br />Prob: 0.0000\",\"Potential.Refusers:   6<br />Prob: 0.0000\",\"Potential.Refusers:   7<br />Prob: 0.0000\",\"Potential.Refusers:   8<br />Prob: 0.0000\",\"Potential.Refusers:   9<br />Prob: 0.0000\",\"Potential.Refusers:  10<br />Prob: 0.0000\",\"Potential.Refusers:  11<br />Prob: 0.0000\",\"Potential.Refusers:  12<br />Prob: 0.0001\",\"Potential.Refusers:  13<br />Prob: 0.0002\",\"Potential.Refusers:  14<br />Prob: 0.0004\",\"Potential.Refusers:  15<br />Prob: 0.0010\",\"Potential.Refusers:  16<br />Prob: 0.0021\",\"Potential.Refusers:  17<br />Prob: 0.0043\",\"Potential.Refusers:  18<br />Prob: 0.0082\",\"Potential.Refusers:  19<br />Prob: 0.0149\",\"Potential.Refusers:  20<br />Prob: 0.0255\",\"Potential.Refusers:  21<br />Prob: 0.0415\",\"Potential.Refusers:  22<br />Prob: 0.0645\",\"Potential.Refusers:  23<br />Prob: 0.0959\",\"Potential.Refusers:  24<br />Prob: 0.1368\",\"Potential.Refusers:  25<br />Prob: 0.1876\",\"Potential.Refusers:  26<br />Prob: 0.2480\",\"Potential.Refusers:  27<br />Prob: 0.3166\",\"Potential.Refusers:  28<br />Prob: 0.3914\",\"Potential.Refusers:  29<br />Prob: 0.4697\",\"Potential.Refusers:  30<br />Prob: 0.5485\",\"Potential.Refusers:  31<br />Prob: 0.6247\",\"Potential.Refusers:  32<br />Prob: 0.6958\",\"Potential.Refusers:  33<br />Prob: 0.7596\",\"Potential.Refusers:  34<br />Prob: 0.8150\",\"Potential.Refusers:  35<br />Prob: 0.8613\",\"Potential.Refusers:  36<br />Prob: 0.8987\",\"Potential.Refusers:  37<br />Prob: 0.9280\",\"Potential.Refusers:  38<br />Prob: 0.9502\",\"Potential.Refusers:  39<br />Prob: 0.9665\",\"Potential.Refusers:  40<br />Prob: 0.9780\",\"Potential.Refusers:  41<br />Prob: 0.9860\",\"Potential.Refusers:  42<br />Prob: 0.9913\",\"Potential.Refusers:  43<br />Prob: 0.9947\",\"Potential.Refusers:  44<br />Prob: 0.9969\",\"Potential.Refusers:  45<br />Prob: 0.9982\",\"Potential.Refusers:  46<br />Prob: 0.9990\",\"Potential.Refusers:  47<br />Prob: 0.9995\",\"Potential.Refusers:  48<br />Prob: 0.9997\",\"Potential.Refusers:  49<br />Prob: 0.9998\",\"Potential.Refusers:  50<br />Prob: 0.9999\",\"Potential.Refusers:  51<br />Prob: 1.0000\",\"Potential.Refusers:  52<br />Prob: 1.0000\",\"Potential.Refusers:  53<br />Prob: 1.0000\",\"Potential.Refusers:  54<br />Prob: 1.0000\",\"Potential.Refusers:  55<br />Prob: 1.0000\",\"Potential.Refusers:  56<br />Prob: 1.0000\",\"Potential.Refusers:  57<br />Prob: 1.0000\",\"Potential.Refusers:  58<br />Prob: 1.0000\",\"Potential.Refusers:  59<br />Prob: 1.0000\",\"Potential.Refusers:  60<br />Prob: 1.0000\",\"Potential.Refusers:  61<br />Prob: 1.0000\",\"Potential.Refusers:  62<br />Prob: 1.0000\",\"Potential.Refusers:  63<br />Prob: 1.0000\",\"Potential.Refusers:  64<br />Prob: 1.0000\",\"Potential.Refusers:  65<br />Prob: 1.0000\",\"Potential.Refusers:  66<br />Prob: 1.0000\",\"Potential.Refusers:  67<br />Prob: 1.0000\",\"Potential.Refusers:  68<br />Prob: 1.0000\",\"Potential.Refusers:  69<br />Prob: 1.0000\",\"Potential.Refusers:  70<br />Prob: 1.0000\",\"Potential.Refusers:  71<br />Prob: 1.0000\",\"Potential.Refusers:  72<br />Prob: 1.0000\",\"Potential.Refusers:  73<br />Prob: 1.0000\",\"Potential.Refusers:  74<br />Prob: 1.0000\",\"Potential.Refusers:  75<br />Prob: 1.0000\",\"Potential.Refusers:  76<br />Prob: 1.0000\",\"Potential.Refusers:  77<br />Prob: 1.0000\",\"Potential.Refusers:  78<br />Prob: 1.0000\",\"Potential.Refusers:  79<br />Prob: 1.0000\",\"Potential.Refusers:  80<br />Prob: 1.0000\",\"Potential.Refusers:  81<br />Prob: 1.0000\",\"Potential.Refusers:  82<br />Prob: 1.0000\",\"Potential.Refusers:  83<br />Prob: 1.0000\",\"Potential.Refusers:  84<br />Prob: 1.0000\",\"Potential.Refusers:  85<br />Prob: 1.0000\",\"Potential.Refusers:  86<br />Prob: 1.0000\",\"Potential.Refusers:  87<br />Prob: 1.0000\",\"Potential.Refusers:  88<br />Prob: 1.0000\",\"Potential.Refusers:  89<br />Prob: 1.0000\",\"Potential.Refusers:  90<br />Prob: 1.0000\",\"Potential.Refusers:  91<br />Prob: 1.0000\",\"Potential.Refusers:  92<br />Prob: 1.0000\",\"Potential.Refusers:  93<br />Prob: 1.0000\",\"Potential.Refusers:  94<br />Prob: 1.0000\",\"Potential.Refusers:  95<br />Prob: 1.0000\",\"Potential.Refusers:  96<br />Prob: 1.0000\",\"Potential.Refusers:  97<br />Prob: 1.0000\",\"Potential.Refusers:  98<br />Prob: 1.0000\",\"Potential.Refusers:  99<br />Prob: 1.0000\",\"Potential.Refusers: 100<br />Prob: 1.0000\",\"Potential.Refusers: 101<br />Prob: 1.0000\",\"Potential.Refusers: 102<br />Prob: 1.0000\",\"Potential.Refusers: 103<br />Prob: 1.0000\",\"Potential.Refusers: 104<br />Prob: 1.0000\",\"Potential.Refusers: 105<br />Prob: 1.0000\",\"Potential.Refusers: 106<br />Prob: 1.0000\",\"Potential.Refusers: 107<br />Prob: 1.0000\",\"Potential.Refusers: 108<br />Prob: 1.0000\",\"Potential.Refusers: 109<br />Prob: 1.0000\",\"Potential.Refusers: 110<br />Prob: 1.0000\",\"Potential.Refusers: 111<br />Prob: 1.0000\",\"Potential.Refusers: 112<br />Prob: 1.0000\",\"Potential.Refusers: 113<br />Prob: 1.0000\",\"Potential.Refusers: 114<br />Prob: 1.0000\",\"Potential.Refusers: 115<br />Prob: 1.0000\",\"Potential.Refusers: 116<br />Prob: 1.0000\",\"Potential.Refusers: 117<br />Prob: 1.0000\",\"Potential.Refusers: 118<br />Prob: 1.0000\",\"Potential.Refusers: 119<br />Prob: 1.0000\",\"Potential.Refusers: 120<br />Prob: 1.0000\",\"Potential.Refusers: 121<br />Prob: 1.0000\",\"Potential.Refusers: 122<br />Prob: 1.0000\",\"Potential.Refusers: 123<br />Prob: 1.0000\",\"Potential.Refusers: 124<br />Prob: 1.0000\",\"Potential.Refusers: 125<br />Prob: 1.0000\",\"Potential.Refusers: 126<br />Prob: 1.0000\",\"Potential.Refusers: 127<br />Prob: 1.0000\",\"Potential.Refusers: 128<br />Prob: 1.0000\",\"Potential.Refusers: 129<br />Prob: 1.0000\",\"Potential.Refusers: 130<br />Prob: 1.0000\",\"Potential.Refusers: 131<br />Prob: 1.0000\",\"Potential.Refusers: 132<br />Prob: 1.0000\",\"Potential.Refusers: 133<br />Prob: 1.0000\",\"Potential.Refusers: 134<br />Prob: 1.0000\",\"Potential.Refusers: 135<br />Prob: 1.0000\",\"Potential.Refusers: 136<br />Prob: 1.0000\",\"Potential.Refusers: 137<br />Prob: 1.0000\",\"Potential.Refusers: 138<br />Prob: 1.0000\",\"Potential.Refusers: 139<br />Prob: 1.0000\",\"Potential.Refusers: 140<br />Prob: 1.0000\",\"Potential.Refusers: 141<br />Prob: 1.0000\",\"Potential.Refusers: 142<br />Prob: 1.0000\",\"Potential.Refusers: 143<br />Prob: 1.0000\",\"Potential.Refusers: 144<br />Prob: 1.0000\",\"Potential.Refusers: 145<br />Prob: 1.0000\",\"Potential.Refusers: 146<br />Prob: 1.0000\",\"Potential.Refusers: 147<br />Prob: 1.0000\",\"Potential.Refusers: 148<br />Prob: 1.0000\",\"Potential.Refusers: 149<br />Prob: 1.0000\",\"Potential.Refusers: 150<br />Prob: 1.0000\",\"Potential.Refusers: 151<br />Prob: 1.0000\",\"Potential.Refusers: 152<br />Prob: 1.0000\",\"Potential.Refusers: 153<br />Prob: 1.0000\",\"Potential.Refusers: 154<br />Prob: 1.0000\",\"Potential.Refusers: 155<br />Prob: 1.0000\",\"Potential.Refusers: 156<br />Prob: 1.0000\",\"Potential.Refusers: 157<br />Prob: 1.0000\",\"Potential.Refusers: 158<br />Prob: 1.0000\",\"Potential.Refusers: 159<br />Prob: 1.0000\",\"Potential.Refusers: 160<br />Prob: 1.0000\",\"Potential.Refusers: 161<br />Prob: 1.0000\",\"Potential.Refusers: 162<br />Prob: 1.0000\",\"Potential.Refusers: 163<br />Prob: 1.0000\",\"Potential.Refusers: 164<br />Prob: 1.0000\",\"Potential.Refusers: 165<br />Prob: 1.0000\",\"Potential.Refusers: 166<br />Prob: 1.0000\",\"Potential.Refusers: 167<br />Prob: 1.0000\",\"Potential.Refusers: 168<br />Prob: 1.0000\",\"Potential.Refusers: 169<br />Prob: 1.0000\",\"Potential.Refusers: 170<br />Prob: 1.0000\",\"Potential.Refusers: 171<br />Prob: 1.0000\",\"Potential.Refusers: 172<br />Prob: 1.0000\",\"Potential.Refusers: 173<br />Prob: 1.0000\",\"Potential.Refusers: 174<br />Prob: 1.0000\",\"Potential.Refusers: 175<br />Prob: 1.0000\",\"Potential.Refusers: 176<br />Prob: 1.0000\",\"Potential.Refusers: 177<br />Prob: 1.0000\",\"Potential.Refusers: 178<br />Prob: 1.0000\",\"Potential.Refusers: 179<br />Prob: 1.0000\",\"Potential.Refusers: 180<br />Prob: 1.0000\",\"Potential.Refusers: 181<br />Prob: 1.0000\",\"Potential.Refusers: 182<br />Prob: 1.0000\",\"Potential.Refusers: 183<br />Prob: 1.0000\",\"Potential.Refusers: 184<br />Prob: 1.0000\",\"Potential.Refusers: 185<br />Prob: 1.0000\",\"Potential.Refusers: 186<br />Prob: 1.0000\",\"Potential.Refusers: 187<br />Prob: 1.0000\",\"Potential.Refusers: 188<br />Prob: 1.0000\",\"Potential.Refusers: 189<br />Prob: 1.0000\",\"Potential.Refusers: 190<br />Prob: 1.0000\",\"Potential.Refusers: 191<br />Prob: 1.0000\",\"Potential.Refusers: 192<br />Prob: 1.0000\",\"Potential.Refusers: 193<br />Prob: 1.0000\",\"Potential.Refusers: 194<br />Prob: 1.0000\",\"Potential.Refusers: 195<br />Prob: 1.0000\",\"Potential.Refusers: 196<br />Prob: 1.0000\",\"Potential.Refusers: 197<br />Prob: 1.0000\",\"Potential.Refusers: 198<br />Prob: 1.0000\",\"Potential.Refusers: 199<br />Prob: 1.0000\",\"Potential.Refusers: 200<br />Prob: 1.0000\"],\"type\":\"scatter\",\"mode\":\"markers\",\"marker\":{\"autocolorscale\":false,\"color\":\"rgba(0,0,0,1)\",\"opacity\":1,\"size\":5.6692913385826778,\"symbol\":\"circle\",\"line\":{\"width\":1.8897637795275593,\"color\":\"rgba(0,0,0,1)\"}},\"hoveron\":\"points\",\"showlegend\":false,\"xaxis\":\"x\",\"yaxis\":\"y\",\"hoverinfo\":\"text\",\"frame\":null}],\"layout\":{\"margin\":{\"t\":23.305936073059364,\"r\":7.3059360730593621,\"b\":37.260273972602747,\"l\":48.949771689497723},\"paper_bgcolor\":\"rgba(255,255,255,1)\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724},\"xaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-10,210],\"tickmode\":\"array\",\"ticktext\":[\"0\",\"50\",\"100\",\"150\",\"200\"],\"tickvals\":[0,49.999999999999993,100,150,200],\"categoryorder\":\"array\",\"categoryarray\":[\"0\",\"50\",\"100\",\"150\",\"200\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"y\",\"title\":{\"text\":\"Refusers\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"yaxis\":{\"domain\":[0,1],\"automargin\":true,\"type\":\"linear\",\"autorange\":false,\"range\":[-0.050000000000000003,1.05],\"tickmode\":\"array\",\"ticktext\":[\"0.00\",\"0.25\",\"0.50\",\"0.75\",\"1.00\"],\"tickvals\":[0,0.25,0.5,0.75,1],\"categoryorder\":\"array\",\"categoryarray\":[\"0.00\",\"0.25\",\"0.50\",\"0.75\",\"1.00\"],\"nticks\":null,\"ticks\":\"\",\"tickcolor\":null,\"ticklen\":3.6529680365296811,\"tickwidth\":0,\"showticklabels\":true,\"tickfont\":{\"color\":\"rgba(77,77,77,1)\",\"family\":\"\",\"size\":11.68949771689498},\"tickangle\":-0,\"showline\":false,\"linecolor\":null,\"linewidth\":0,\"showgrid\":true,\"gridcolor\":\"rgba(235,235,235,1)\",\"gridwidth\":0,\"zeroline\":false,\"anchor\":\"x\",\"title\":{\"text\":\"Prob. of x or Less Refusers\",\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":14.611872146118724}},\"hoverformat\":\".2f\"},\"shapes\":[{\"type\":\"rect\",\"fillcolor\":null,\"line\":{\"color\":null,\"width\":0,\"linetype\":[]},\"yref\":\"paper\",\"xref\":\"paper\",\"layer\":\"below\",\"x0\":0,\"x1\":1,\"y0\":0,\"y1\":1}],\"showlegend\":false,\"legend\":{\"bgcolor\":null,\"bordercolor\":null,\"borderwidth\":0,\"font\":{\"color\":\"rgba(0,0,0,1)\",\"family\":\"\",\"size\":11.68949771689498}},\"hovermode\":\"closest\",\"barmode\":\"relative\"},\"config\":{\"doubleClick\":\"reset\",\"modeBarButtonsToAdd\":[\"hoverclosest\",\"hovercompare\"],\"showSendToCloud\":false},\"source\":\"A\",\"attrs\":{\"17a295fa3c43e\":{\"x\":{},\"y\":{},\"type\":\"scatter\"}},\"cur_data\":\"17a295fa3c43e\",\"visdat\":{\"17a295fa3c43e\":[\"function (y) \",\"x\"]},\"highlight\":{\"on\":\"plotly_click\",\"persistent\":false,\"dynamic\":false,\"selectize\":false,\"opacityDim\":0.20000000000000001,\"selected\":{\"opacity\":1},\"debounce\":0},\"shinyEvents\":[\"plotly_hover\",\"plotly_click\",\"plotly_selected\",\"plotly_relayout\",\"plotly_brushed\",\"plotly_brushing\",\"plotly_clickannotation\",\"plotly_doubleclick\",\"plotly_deselect\",\"plotly_afterplot\",\"plotly_sunburstclick\"],\"base_url\":\"https://plot.ly\"},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n        \n:::\n::::\n\n## More Questions About Scottish Pounds\n\n2. What is the probability that 24 or fewer will not accept Scottish pounds?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npbinom(24, 200, 0.15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.1368173\n```\n\n\n:::\n:::\n\n\n\n\n3. What is the probability that 25 or more shopkeepers will not accept Scottish pounds?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n1-pbinom(24, 200, 0.15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8631827\n```\n\n\n:::\n:::\n\n\n\n\n4. With probability 0.9 [90 percent], XXX or fewer shopkeepers will not accept Scottish pounds.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqbinom(0.9, 200, 0.15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 37\n```\n\n\n:::\n:::\n\n\n\n## Application: The Median is a Binomial with p=0.5\n\nInterestingly, any given observation has a 50-50 chance of being *over* or *under* the median.  Suppose that I have five datum.  \n\n1. What is the probability that all are under?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npbinom(0,size=5, p=0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.03125\n```\n\n\n:::\n:::\n\n\n2. What is the probability that all are over?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbinom(5,size=5, p=0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.03125\n```\n\n\n:::\n:::\n\n\n3. What is the probability that the median is somewhere in between our smallest and largest sampled values?\n\n**Everything else**.  $1 - (0.03125 + 0.03125) = 0.9375$\n\n## The Rule of Five\n\n| Number Bigger | Probability |\n|-----|---------|\n| 0 | 1*0.03125 |\n| 1 | 5*0.03125 |\n| 2 | 10*0.03125 |\n| 3 | 10*0.03125 |\n| 4 | 5*0.03125 |\n| 5 | 1*0.03125 |\n\n\n\n- This is called the *Rule of Five* by Hubbard in his *How to Measure Anything*.\n\n\n\n## Geometric Distributions\n\nHow many failures before the first success?  Now defined exclusively by $p$.  In each case, (1-p) happens $k$ times.  Then, on the $k+1^{th}$ try, p.  Note 0 failures can happen...\n\n$$Pr(y=k) = (1-p)^{k}p$$\n\n\n\n## Example: Entrepreneurs\n\nSuppose any startup has a $p=0.1$ chance of success.  How many failures?\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/GP1-1.svg){width=624}\n:::\n:::\n\n\n\n\n## Example: Entrepreneurs\n\nSuppose any startup has a $p=0.1$ chance of success.  How many failures for the average/median person?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nqgeom(0.5,0.1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6\n```\n\n\n:::\n:::\n\n\n\n\n5. [Geometric] Plot 1000 random draws of \"How many vendors until one refuses my Scottish pounds?\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGeoms.My <- data.frame(Vendors=rgeom(1000, 0.15))\nGeoms.My %>% ggplot() + aes(x=Vendors) + geom_histogram(binwidth=1)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-10-1.svg){width=624}\n:::\n:::\n\n\n\n\nWe could also do something like.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(seq(0,60), pgeom(seq(0,60), 0.15))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-11-1.svg){width=624}\n:::\n:::\n\n\n\n## Negative Binomial Distributions\n\nHow many failures before the $r^{th}$ success?  In each case, (1-p) happens $k$ times.  Then, on the $k+1^{th}$ try, we get our $r^{th}$ p.  Note 0 failures can happen...\n\n$$Pr(y=k) = {k+r-1 \\choose r-1}(1-p)^{k}p^{r}$$\n\n## Needed Sales\n\nI need to make 5 sales to close for the day.  How many potential customers will I have to have to get those five sales when each customer purchases with probability 0.2.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(patchwork)\nDF <-  data.frame(Customers = c(0:70)) %>% \n  mutate(m.Customers = dnbinom(Customers, size=5, prob=0.2), \n         p.Customers = pnbinom(Customers, size=5, prob=0.2)) \npl1 <- DF %>% ggplot() + aes(x=Customers) + geom_line(aes(y=p.Customers)) \npl2 <- DF %>% ggplot() + aes(x=Customers) + geom_point(aes(y=m.Customers))\n```\n:::\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-13-1.svg){width=624}\n:::\n:::\n\n\n\n## Simulation: A Powerful Tool\n\nIn this last example, I was concerned with sales.  I might also want to generate revenues because I know the rough mean and standard deviation of sales.  Combining such things together forms the basis of a Monte Carlo simulation.\n\n\n## An Example\n\nCustomers arrive at a rate of 7 per hour.\nYou convert customers to buyers at a rate of 85%.\nBuyers spend, on average 600 dollars with a standard deviation of 150 dollars.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSim <- 1:1000\nCustomers <- rpois(1000, 7)\nBuyers <- rbinom(1000, size=Customers, prob = 0.85)\nData <- data.frame(Sim, Buyers, Customers)\nData <- Data %>% group_by(Sim) %>% mutate(Revenue = sum(rnorm(Buyers, 600, 150))) %>% ungroup()\n```\n:::\n\n\n\n# Simulation Results\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/Plot1-1.svg){width=624}\n:::\n:::\n\n\n## A Summary\n\nDistributions are how variables and probability relate.  They are a graph that we can enter in two ways.  From the probability side to solve for values or from values to solve for probability.  It is always a function of the graph.\n\nDistributions generally have to be sentences. \n\n- The name is a noun but it also has \n- parameters -- verbs -- that makes the noun tangible.\n\n# Inference of Two Types: Binary and Numeric\n\n# Discrete Inference [Binary]\n\n\n\n\n## How do we learn from data?\n\n\n![](https://media.giphy.com/media/frBS2qxvbV9SzizdSX/giphy.gif)\n\n\n* **It is probably better posed as, what can we learn from data?**.  \n\n## The Big Idea\n\n### Inference\n\nIn the most basic form, learning something about data that we do not have from data that we do.  In the jargon of statistics, we characterize the probability distribution of some feature of the population of interest from a sample drawn randomly from that population. \n\n### Quantities of Interest:  \n\n- **Single Proportion**: *The probability of some qualitative outcome with appropriate uncertainty.^[Which will itself be a probability measure.]*   \n\n- **Single Mean**: *The average of some quantitative outcome with appropriate uncertainty.<sup>1</sup>*    \n\n## The Big Idea\n  \n### **Inference**\n  \nIn the most basic form, learning something about data that we do not have from data that we do.  In the jargon of statistics, we characterize the probability distribution of some feature of the population of interest from a sample drawn randomly from that population.  \n\n### Quantities of Interest:  \n\n- **Compare Proportions**: *Compare key probabilities across two groups with appropriate uncertainty.^[Which will itself be a probability measure.]*\n\n- **Compare Means**: *Compare averages/means across two groups with appropriate uncertainty.<sup>1</sup>*\n\n## The Big Idea\n  \n### **Inference**\n  \nIn the most basic form, learning something about data that we do not have from data that we do.  In the jargon of statistics, we characterize the probability distribution of some feature of the population of interest from a sample drawn randomly from that population. \n\n### Study Planning  \n\n*Plan studies of adequate size to assess key probabilities of interest.*   \n  \n## Inference for Data\n  \nOf two forms:\n  \n1. Binary/Qualitative\n2. Quantitative\n\nWe will first focus first on the former.  But before we do, one new concept.  \n\n## The **standard error**  \n\nIt is the *degree of variability of a statistic* just as the standard deviation is the *variability in data*. \n\n- The standard error of a proportion is $\\sqrt{\\frac{\\pi(1-\\pi)}{n}}$ while the standard deviation of a binomial sample would be $\\sqrt{n*\\pi(1-\\pi)}$. \n\n- The standard deviation of a sample is $s$ while the standard error of the mean is $\\frac{s}{\\sqrt{n}}$.  The average has less variability than the data and it shrinks as n increases.\n\n## Let's think about an election....\n\nConsider election season.  *The key to modeling the winner of a presidential election is the electoral college in the United States.*  In almost all cases, this involves a series of binomial variables.\n\n- Almost all states award electors for the statewide winner of the election and DC has electoral votes.\n\n- We have polls that give us likely vote percentages at the state level.  Call it `p.win` for the probability of winning.  We can then deploy `rbinom(1000, size=1, p.win)` to derive a hypothetical election.  \n\n- Rinse and repeat to calculate a hypothetical electoral college winner.  But how do we calculate `p-win`?\n  \n- **We infer it from polling data**\n\n## An Interesting Post on the Mechanics\n\n[Post](https://www.niemanlab.org/2020/07/this-is-how-fivethirtyeight-is-trying-to-build-the-right-amount-of-uncertainty-into-its-2020-election-data-analysis/)\n  \n## Qualitative: The Binomial\n  \nIs entirely defined by two parameters, $n$ -- the number of subjects -- and $\\pi$ -- the probability of a positive response.  The probability of exactly $x$ positive responses is given by:\n  \n$$ Pr(X = x | \\pi, n) = {n \\choose x} \\pi^x (1-\\pi)^{n-x} $$\n  \nThe binomial is the `canonical` distribution for binary outcomes.  *Assuming all $n$ subjects are alike and the outcome occurs with $\\pi$ probability*,^[If this does not hold, we will seek the homogenous groups in which it does.] then we must have a sample from a binomial.  *A binomial with $n=1$ is known as a Bernoulli trial* \n\n## Features of the Binomial\n\nTwo key features:\n\n1. Expectation: $n \\cdot \\pi$ or number of subjects times probability, $\\pi \\textrm{ if } n=1$.\n\n2. Variance is $n \\cdot \\pi \\cdot (1 - \\pi)$  or $\\pi(1-\\pi) \\textrm{ if } n=1$ and standard deviation is $\\sqrt{n \\cdot \\pi \\cdot (1 - \\pi)}$ or $\\sqrt{\\pi(1-\\pi)} \\textrm{ if } n=1$.\n\n## Data\n\nNow let's grab some data and frame a question.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload(url(\"https://github.com/robertwwalker/DADMStuff/raw/master/Big-Week-6-RSpace.RData\"))\n```\n:::\n\n\n\n## Berkeley Admissions {.smaller}\n  \nWhat is the probability of being admitted to UC Berkeley Graduate School?^[We probably think this depends on a bunch of applicant specific features but we will put that to the side for now.]  \n\n. . .   \n  \nI have three variables: \n\n1. Admitted or not\n\n2. Gender \n\n3. The department an applicant applied to.\n\n<span style=\"color: green;\">Admission is the key.</span>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(janitor)  #<<\nUCBTab <- data.frame(UCBAdmissions) %>%\n    reshape::untable(., .$Freq) %>%\n    select(-Freq)\nUCBTab %>%\n    tabyl(Admit)  # Could also use UCBTab %$% table(Admit) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    Admit    n percent\n Admitted 1755   0.388\n Rejected 2771   0.612\n```\n\n\n:::\n:::\n\n\nThe proportion is denoted as $\\hat{p}$.  We can also do this with *table*.\n\n---\n\n\n::: {.cell}\n\n```{.r .cell-code}\nUCBTab %>%\n    DT::datatable(., fillContainer = FALSE, options = list(pageLength = 8),\n        rownames = FALSE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"datatables html-widget html-fill-item\" id=\"htmlwidget-09b544bac8f6435d6634\" style=\"width:100%;height:auto;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-09b544bac8f6435d6634\">{\"x\":{\"filter\":\"none\",\"vertical\":false,\"fillContainer\":false,\"data\":[[\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Admitted\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\",\"Rejected\"],[\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Male\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\",\"Female\"],[\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"B\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"C\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"D\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"E\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\",\"F\"]],\"container\":\"<table class=\\\"display\\\">\\n  <thead>\\n    <tr>\\n      <th>Admit<\\/th>\\n      <th>Gender<\\/th>\\n      <th>Dept<\\/th>\\n    <\\/tr>\\n  <\\/thead>\\n<\\/table>\",\"options\":{\"pageLength\":8,\"columnDefs\":[{\"name\":\"Admit\",\"targets\":0},{\"name\":\"Gender\",\"targets\":1},{\"name\":\"Dept\",\"targets\":2}],\"order\":[],\"autoWidth\":false,\"orderClasses\":false,\"lengthMenu\":[8,10,25,50,100]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n:::\n:::\n\n\n## A Visual\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(viridisLite)\nUCBTab %>%\n    ggplot(.) + aes(x = Gender, fill = Admit) + geom_bar() + scale_fill_viridis_d()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-18-1.svg){fig-align='center' width=624}\n:::\n:::\n\n\n## The Idea\n\nSuppose we want to know $\\pi(Admit)$ -- the probability of being admitted -- with 90% probability.  \n\nWe want to take the data that we saw and use it to **infer** the likely values of $\\pi(Admit)$.  \n\n## Three interchangeable methods\n\n1. Resampling/Simulation\n\n2. Exact binomial computation\n\n3. A normal approximation\n\n\n## Method 1: Resampling\n\n**Suppose I have 4526 chips with 1755 <span style=\"color: green;\">green</span> and 2771 <span style=\"color: red;\">red</span>.**  \n\n. . .\n\nI toss them all on the floor\n\n. . .\n\nand pick them up, one at a time, \n\n. . .\n\nrecord the value (<span style=\"color: green;\">green</span>/<span style=\"color: red;\">red</span>), \n\n. . .\n\nput the chip back,  \n*[NB: I put it back to avoid getting exactly the same `sample` every time.]*\n\n. . .\n\nand repeat 4526 times.  \n\n\n\n**Each count of <span style=\"color: green;\">green chips</span> as a proportion of 4526 total chips constitutes an estimate of the probability of Admit.**\n\n. . .\n\nI wrote a little program to do just this -- `ResampleProps`.  \n```\nremotes::install_github(\"robertwwalker/ResampleProps\")\n```\n\n## Resampling Result\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ResampleProps)\nRSMP <- ResampleProp(UCBTab$Admit, k = 10000, tab.col = 1) %>%\n    data.frame(Pi.Admit = ., Gender = as.character(\"All\"), frameN = 1)\nquantile(RSMP$Pi.Admit, probs = c(0.05, 0.95))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   5%   95% \n0.376 0.400 \n```\n\n\n:::\n:::\n\n\nWhat is our estimate of $\\pi$ with 90% confidence?   \n\n*The probability of admission ranges from 0.376 to 0.4.*\n\n\n## A Plot\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggthemes)\nRSMP %>%\n    ggplot(., aes(x = Pi.Admit)) + geom_density(outline.type = \"upper\", color = \"maroon\") +\n    labs(x = expression(pi)) + theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-20-1.svg){fig-align='center' width=624}\n:::\n:::\n\n\n\n\n## Another Way: Exact binomial\n\nThat last procedure is correct but it is overkill.\n\n1. With probability of 0.05, how small could $\\pi$ be to have gotten 1755 of 4526 or more?  \n\n2. With probability 0.95, how big could $\\pi$ be to have gotten  fewer than 1755 of 4526?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nUCBTab %$%\n    table(Admit)  #<<\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAdmit\nAdmitted Rejected \n    1755     2771 \n```\n\n\n:::\n:::\n\n\n. . .\n\n**`binom.test` does exactly this.**\n\n## `binom.test()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nUCBTab %$%\n    table(Admit) %>%\n    binom.test(conf.level = 0.9)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tExact binomial test\n\ndata:  .\nnumber of successes = 1755, number of trials = 4526, p-value\n<2e-16\nalternative hypothesis: true probability of success is not equal to 0.5\n90 percent confidence interval:\n 0.376 0.400\nsample estimates:\nprobability of success \n                 0.388 \n```\n\n\n:::\n\n```{.r .cell-code}\nPlot.Me <- binom.test(1755, 1755 + 2771, conf.level = 0.9)$conf.int %>%\n    data.frame()\n```\n:::\n\n\n**With 90% probability, now often referred to as 90% confidence to avoid using the word probability twice, the probability of being admitted ranges between 0.3758 and 0.3998.**\n\n## Illustrating the Binomial\n\n\n::: {.cell}\n\n```{.r .cell-code}\nUCBTab %$%\n    table(Admit) %>%\n    binom.test(conf.level = 0.9)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tExact binomial test\n\ndata:  .\nnumber of successes = 1755, number of trials = 4526, p-value\n<2e-16\nalternative hypothesis: true probability of success is not equal to 0.5\n90 percent confidence interval:\n 0.376 0.400\nsample estimates:\nprobability of success \n                 0.388 \n```\n\n\n:::\n\n```{.r .cell-code}\nc(pbinom(1755, 1755 + 2771, 0.399834), pbinom(1754, 1755 + 2771, 0.3757924))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.05 0.95\n```\n\n\n:::\n:::\n\n\n---\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nBinomial.Search <- data.frame(x = seq(0.33, 0.43, by = 0.001)) %>%\n    mutate(Too.Low = pbinom(1755, 1755 + 2771, x), Too.High = 1 - pbinom(1754,\n        1755 + 2771, x))\nBinomial.Search %>%\n    pivot_longer(cols = c(Too.Low, Too.High)) %>%\n    ggplot(., aes(x = x, y = value, color = name)) + geom_line() + geom_hline(aes(yintercept = 0.05)) +\n    geom_hline(aes(yintercept = 0.95)) + geom_vline(data = Plot.Me, aes(xintercept = .),\n    linetype = 3) + labs(title = \"Using the Binomial to Search\", color = \"Greater/Lesser\",\n    x = expression(pi), y = \"Probability\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-24-1.svg){fig-align='center' width=960}\n:::\n:::\n\n\n## A Third Way: The normal approximation\n\nAs long as $n$ and $\\pi$ are sufficiently large, we can approximate this with a normal distribution.  **This will also prove handy for a related reason.**  \n\nAs long as $n*\\pi$ > 10, we can write that a standard normal $z$ describes the distribution of $\\pi$, given $n$ -- the sample size and $\\hat{p}$ -- the proportion of yes's/true's in the sample.\n\n$$ Pr(\\pi) = \\hat{p} \\pm z \\cdot \\left( \\sqrt{\\frac{\\hat{p}*(1-\\hat{p})}{n}} \\right) $$\n\n$R$ implements this in `prop.test`.  By default, R implements a modified version that corrects for discreteness/continuity.  To get the above formula exactly, `prop.test(table, correct=FALSE)`.\n\n## A first look at hypotheses {.smaller}\n\n$$ z = \\frac{\\hat{p} - \\pi}{\\sqrt{\\frac{\\pi(1-\\pi)}{n}}} $$\n\nWith some proportion calculated from data $\\hat{p}$ and some claim about $\\pi$ -- hereafter called an **hypothesis** -- we can use $z$ to calculate/evaluate the claim. These claims are *hypothetical* values of $\\pi$.  They can be evaluated against a specific alternative considered in three ways:\n\n- two-sided, that is $\\pi = value$ against not equal.  \n\n- $\\pi \\geq value$ against something smaller.  \n\n- $\\pi \\leq value$ against something greater.  \n\nIn the first case, either much bigger or much smaller values could be evidence against equal.  The second and third cases are always about smaller and bigger; they are one-sided.\n\nJust as $z$ has metric standard deviations now referred to as standard errors of the proportion, the z here will measure where the data fall with respect to the hypothetical $\\pi$.  \n\n*With z sufficiently large, and in the proper direction, our hypothetical $\\pi$ becomes unlikely given the evidence and should be dismissed.*\n\n## Three hypothesis tests\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(Z.ALL <- (0.3877596 - 0.5)/(sqrt(0.5^2/4526)))  # Calculate z \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -15.1\n```\n\n\n:::\n:::\n\n\n*The estimate is 15.1 standard errors below the hypothesized value.*\n\n::::{.columns}\n\n::: {.column width=\"50%\"}\n\n### Two Sided\n\n$\\pi = 0.5$ against $\\pi \\neq 0.5$.\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(-abs(Z.ALL)) + (1 - pnorm(abs(Z.ALL)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7.85e-52\n```\n\n\n:::\n:::\n\n\nAny $|z| > 1.64$ -- probability 0.05 above and below -- is sufficient to dispense with the hypothesis.\n\n:::\n\n::: {.column width=\"50%\"}\n\n### One-Sided\n\n$\\pi \\leq 0.5$ against $\\pi \\gt 0.5$.\n\nWith 90% confidence, $z > 1.28$ is sufficient.\n\n$\\pi \\geq 0.5$ against $\\pi \\lt 0.5$.\n\nWith 90% confidence, $z < -1.28$ is sufficient.\n\n:::\n\n::::\n\n## The normal approximation {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(table(UCBTab$Admit), conf.level = 0.9, correct = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t1-sample proportions test without continuity correction\n\ndata:  table(UCBTab$Admit), null probability 0.5\nX-squared = 228, df = 1, p-value <2e-16\nalternative hypothesis: true p is not equal to 0.5\n90 percent confidence interval:\n 0.376 0.400\nsample estimates:\n    p \n0.388 \n```\n\n\n:::\n:::\n\n\n$R$ reports the result as $z^2$ not $z$ which is $\\chi^2$ not normal; we can obtain the $z$ by taking a square root: $$\\sqrt{228.08} \\approx 15.1 $$\n\nThis approximation yields an estimate of $\\pi$, with 90% confidence, that ranges between 0.376 and 0.4.\n\n\n## A Cool Consequence of Normal {.smaller}\n\nThe formal equation defines:\n\n$$ z = \\frac{\\hat{p} - \\pi}{\\sqrt{\\frac{\\pi(1-\\pi)}{n}}} $$\n\nSome language:\n\n1. Margin of error is $\\hat{p} - \\pi$.  [MOE]\n\n2. Confidence: the probability coverage given z [two-sided].\n\n3. We need a guess at the true $\\pi$ because variance/std. dev. depend on $\\pi$.  0.5 is common because it maximizes the variance; we will have enough no matter what the true value.\n\nAlgebra allows us to solve for $n$.\n\n$$ n = \\frac{z^2 \\cdot \\pi(1-\\pi)}{(\\hat{p} - \\pi)^2} $$\n\n## Example\n\nEstimate the probability of supporting an initiative to within 0.03 with 95% confidence.  Assume that the probability is 0.5 [it maximizes the variance and renders a conservative estimate -- an upper bound on the sample size]\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSample.Size <- function(MOE, B.pi = 0.5, Conf.lev = 0.95) {\n    My.n <- ((qnorm((1 - Conf.lev)/2)^2) * (B.pi * (1 - B.pi)))/MOE^2\n    Necessary.sample <- ceiling(My.n)\n    return(Necessary.sample)\n}\nSample.Size(MOE = 0.03, B.pi = 0.5, Conf.lev = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1068\n```\n\n\n:::\n:::\n\n\n**I need 1068 people to estimate support to within plus or minus 0.03 with 95% confidence.**\n\n## In the Real World\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](./y1.png){width=900px height=300px}\n:::\n:::\n\n\n[A real poll](https://navigatorresearch.org/wp-content/uploads/2020/04/Navigator-Daily-Tracker-Topline-F04.13.20.pdf).  They do not have quite enough for a 3% margin of error.  But 1006 is enough for a 3.1 percent margin of error...\n\n\n::: {.cell}\n\n```{.r .cell-code}\nSample.Size(MOE = 0.031, B.pi = 0.5, Conf.lev = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1000\n```\n\n\n:::\n:::\n\n\n\n## One More Oddity\n\nWhat is our estimate of $\\pi$ with 90% confidence?  \n\n**The probability of admission ranges from 0.376 to 0.4.**\n\nIf we wish to express this using the normal approximation, a central interval is the observed proportion plus/minus $z$ times the *standard error of the proportion* -- $$ SE(\\hat{p}) = \\sqrt{\\frac{\\hat{p}(1-\\hat{p})}{n}} $$  NB: The sample value replaces our assumed true value because $\\pi$ is to be solved for.  For 90%, the probability of admissions ranges from\n\n\n::: {.cell}\n\n```{.r .cell-code}\n0.3877596 + qnorm(c(0.05, 0.95)) * (sqrt(0.3877596 * (1 - 0.3877596)/4526))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.376 0.400\n```\n\n\n:::\n:::\n\n\n# Back to the Story\n\n**Does the probability of admission depend on whether the applicant is Male or Female?**\n\n## Analysis by Group\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(janitor)\nUCBTab %>%\n    tabyl(Gender, Admit) %>%\n    adorn_totals(\"col\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Gender Admitted Rejected Total\n   Male     1198     1493  2691\n Female      557     1278  1835\n```\n\n\n:::\n\n```{.r .cell-code}\nUCBTab %>%\n    tabyl(Gender, Admit) %>%\n    adorn_percentages(\"row\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n Gender Admitted Rejected\n   Male    0.445    0.555\n Female    0.304    0.696\n```\n\n\n:::\n\n```{.r .cell-code}\nUCBTF <- UCBTab %>%\n    filter(Gender == \"Female\")\nUCBTF.Pi <- ResampleProp(UCBTF$Admit, k = 10000) %>%\n    data.frame(Pi.Admit = ., Gender = as.character(\"Female\"), frameN = 2)  # Estimates for females\nUCBTM <- UCBTab %>%\n    filter(Gender == \"Male\")\nUCBTM.Pi <- ResampleProp(UCBTM$Admit, k = 10000) %>%\n    data.frame(Pi.Admit = ., Gender = as.character(\"Male\"), frameN = 2)  # Estimates for males\n```\n:::\n\n\n## Binomial Result: Males\n\n\n::: {.cell}\n\n```{.r .cell-code}\nUCBTM %$%\n    table(Admit) %>%\n    binom.test(., conf.level = 0.9)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tExact binomial test\n\ndata:  .\nnumber of successes = 1198, number of trials = 2691, p-value =\n0.00000001\nalternative hypothesis: true probability of success is not equal to 0.5\n90 percent confidence interval:\n 0.429 0.461\nsample estimates:\nprobability of success \n                 0.445 \n```\n\n\n:::\n:::\n\n\nThe probability of being admitted, conditional on being Male, ranges from 0.43 to 0.46 with 90% confidence.\n\n\n## The Thought Experiment: Male\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nUCBTM.Pi %>%\n    ggplot(., aes(x = Pi.Admit)) + geom_density(color = \"maroon\") + labs(x = expression(pi))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/BMPlot-1.svg){fig-align='center' width=624}\n:::\n:::\n\n\n\n## Binomial Result: Females\n\n\n::: {.cell}\n\n```{.r .cell-code}\nUCBTF %$%\n    table(Admit) %>%\n    binom.test(., conf.level = 0.9)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tExact binomial test\n\ndata:  .\nnumber of successes = 557, number of trials = 1835, p-value <2e-16\nalternative hypothesis: true probability of success is not equal to 0.5\n90 percent confidence interval:\n 0.286 0.322\nsample estimates:\nprobability of success \n                 0.304 \n```\n\n\n:::\n:::\n\n\nThe probability of being of Admitted, given a Female, ranges from 0.286 to 0.322 with 90% confidence.\n\n## The Thought Experiment: Female\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nUCBTF.Pi %>%\n    ggplot(., aes(x = Pi.Admit)) + geom_density(color = \"maroon\") + labs(x = expression(pi))\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/BFPlot-1.svg){fig-align='center' width=624}\n:::\n:::\n\n\n## Succinctly\n\n:::: {.columns}\n\n::: {.column width=\"30%\"}\n\nFemale: from 0.286 to 0.322  \nMale: from 0.43 to 0.46  \nAll: from 0.3758 to 0.3998  \n:::\n\n::: {.column width=\"70%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/patch1-1.svg){width=864}\n:::\n:::\n\n\n:::\n\n::::\n\n## A Key Visual\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nUCB.Pi <- bind_rows(UCBTF.Pi, UCBTM.Pi)\nUCB.Pi %>%\n    ggplot(., aes(x = Gender, y = Pi.Admit, fill = Gender)) + geom_violin() +\n    geom_label(aes(x = 1.5, y = 0.375), label = \"Too small to be male \\n Too large to be female?\",\n        size = 14, fill = \"black\", color = \"white\", inherit.aes = FALSE) + guides(size = \"none\") +\n    labs(x = \"\") + scale_fill_viridis_d()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-revealjs/Yellow-1.jpeg){fig-align='center' width=864}\n:::\n:::\n\n\n---\n\n:::: {.columns}\n\n::: {.column width=\"30%\"}\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nUCB.Pi <- bind_rows(UCBTF.Pi, UCBTM.Pi, RSMP)\nUCB.Pi %>%\n    ggplot(., aes(x = Pi.Admit, fill = Gender)) + geom_density(alpha = 0.5) +\n    theme_minimal() + scale_fill_viridis_d() + transition_states(frameN, state_length = 40,\n    transition_length = 20) + enter_fade() + exit_fade() -> SaveAnim\nanim_save(SaveAnim, renderer = gifski_renderer(height = 500, width = 1000),\n    filename = \"img/Anim1.gif\")\n```\n:::\n\n\n:::\n\n::: {.column width=\"70%\"}\n\n![](img/Anim1.gif)\n\n:::\n\n::::\n\n## Can We Measure the Difference?\n\n:::: {.columns}\n\n::: {.column width=\"50%\"}\nHow much more likely are Males to be admitted when compared to Females?\n\n**We can take the difference in our estimates for Male and Female.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\nUCB.Diff <- UCB.Pi %>% filter(frameN != 1) %>% select(Pi.Admit, Gender) %>% mutate(obs = rep(seq(1:10000),2)) %>% pivot_wider(., id_cols = obs, values_from=Pi.Admit, names_from=Gender) %>% mutate(Diff = Male - Female)\nquantile(UCB.Diff$Diff, probs=c(0.05,0.95))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   5%   95% \n0.118 0.165 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(UCB.Diff) + aes(x = Diff) + geom_density() + labs(title = \"Difference in Probability of Admission\",\n    subtitle = \"[Male - Female]\")\n```\n:::\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-revealjs/unnamed-chunk-33-1.svg){width=624}\n:::\n:::\n\n:::\n\n::::\n\n## Or Use the Normal Approximation\n\n$$[\\hat{p}_{M} - \\hat{p}_{F}] \\pm z*\\sqrt{ \\underbrace{\\frac{\\hat{p}_{M}(1-\\hat{p}_{M})}{n_{M}}}_{Males} + \\underbrace{\\frac{\\hat{p}_{F}(1-\\hat{p}_{F})}{n_{F}}}_{Females}}$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# prop.test(table(UCBTab$Gender,UCBTab$Admit), conf.level=0.9,\n# correct=FALSE)\nUCBTab %$%\n    table(Gender, Admit) %>%\n    prop.test(conf.level = 0.9, correct = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\t2-sample test for equality of proportions without continuity\n\tcorrection\n\ndata:  .\nX-squared = 92, df = 1, p-value <2e-16\nalternative hypothesis: two.sided\n90 percent confidence interval:\n 0.118 0.165\nsample estimates:\nprop 1 prop 2 \n 0.445  0.304 \n```\n\n\n:::\n:::\n\n\nWith 90% confidence, a Female is 0.118 to 0.165 [0.1416] less likely to be admitted.\n\n## The Standard Error of the Difference\n\nFollowing something akin to the FOIL method, we can show that the variance of a difference in two random variables is the sum of the variances minus twice the covariance between them.\n\n$$Var(X - Y) = Var(X) + Var(Y) - 2*Cov(X,Y) $$\n\nIf we assume [or recognize it is generally unknownable] that the male and female samples are independent, the covariance is zero, and the variance of the difference is simply the sum of the variance for male and female, respectively, and **zero covariance**.\n\n$$SE(\\hat{p}_{M} - \\hat{p}_{F}) =  \\sqrt{ \\underbrace{\\frac{\\hat{p}_{M}(1-\\hat{p}_{M})}{n_{M}}}_{Males} + \\underbrace{\\frac{\\hat{p}_{F}(1-\\hat{p}_{F})}{n_{F}}}_{Females}}$$  \n\n## The chi-square and the test of independence\n\nThe sum of $k$ squared standard normal (z or Normal(0,1)) variates has a $\\chi^2$ distribution with $k$ degrees of freedom.  Two sample tests of proportions can be reported using the chi-square metric as well.  $R$'s `prop.test` does this by default.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/plotly-binding-4.11.0/plotly.js\"></script>\n<script src=\"../../site_libs/typedarray-0.1/typedarray.min.js\"></script>\n<script src=\"../../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"../../site_libs/crosstalk-1.2.2/css/crosstalk.min.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/crosstalk-1.2.2/js/crosstalk.min.js\"></script>\n<link href=\"../../site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/plotly-main-2.11.1/plotly-latest.min.js\"></script>\n<link href=\"../../site_libs/datatables-css-0.0.0/datatables-crosstalk.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/datatables-binding-0.34.0/datatables.js\"></script>\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.min.css\" rel=\"stylesheet\" />\n<link href=\"../../site_libs/dt-core-1.13.6/css/jquery.dataTables.extra.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/dt-core-1.13.6/js/jquery.dataTables.min.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}