{
  "hash": "4e109878317d720d692f059668112590",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Gemini Multi-Agent Binomial Analysis\"\nauthor: \"Robert W. Walker\"\ndate: \"2026-03-03\"\nimage: \"image.png\"\nformat:\n    html:\n     fig-format: retina\n     fig-dpi: 600\n     fig-height: 6\n     fig-width: 8\n---\n\n\n\n\n::: {.callout-note appearance=\"simple\"}\n## Prompt\n\nI want three subagent statisticians.  A Bayesian, a frequentist, and a computational simulation specialist.  I would like each to estimate the probability of Admit from the attached csv file overall, separately for Female and Male applicants, and the difference in the probability of Admit between Male and Female.  Finally, show the difference in probability estimated separately for each Department (Dept) A, B, C, D, E, and F.  Please check calculations along the way and use the attached data.  In each case, provide a 90% confidence or credible interval\n:::\n\n\n## Markdown Response\n\n# UC Berkeley Admission Analysis\n\nThis report presents an analysis of the UCB-Admit dataset from three statistical perspectives: Frequentist, Bayesian, and Computational Simulation. The goal is to estimate admission probabilities and investigate potential gender differences.\n\n## 1. Overall Admission Probabilities (90% Confidence/Credible Intervals)\n\n| Approach | Group | Estimate | 90% Interval |\n| :--- | :--- | :--- | :--- |\n| **Frequentist** | Overall | 0.3878 | [0.3758, 0.3997] |\n| | Male | 0.4452 | [0.4294, 0.4609] |\n| | Female | 0.3035 | [0.2859, 0.3212] |\n| **Bayesian** | Overall | 0.3878 | [0.3759, 0.3997] |\n| | Male | 0.4452 | [0.4295, 0.4610] |\n| | Female | 0.3038 | [0.2862, 0.3215] |\n| **Simulation** | Overall | 0.3877 | [0.3760, 0.3997] |\n| | Male | 0.4450 | [0.4292, 0.4609] |\n| | Female | 0.3036 | [0.2864, 0.3215] |\n\n---\n\n## 2. Difference in Probability (Male - Female)\n\nA positive value indicates a higher admission rate for males.\n\n| Approach | Estimate (M-F) | 90% Interval |\n| :--- | :--- | :--- |\n| **Frequentist** | +0.1416 | [0.1180, 0.1653] |\n| **Bayesian** | +0.1415 | [0.1178, 0.1647] |\n| **Simulation** | +0.1414 | [0.1174, 0.1656] |\n\n---\n\n## 3. Difference in Probability by Department (Male - Female)\n\nThe department-level analysis reveals **Simpson's Paradox**: while the aggregate data suggests a bias toward males, most individual departments show either no significant difference or a slight advantage for females.\n\n| Dept | Frequentist (90% CI) | Bayesian (90% CrI) | Simulation (90% CI) |\n| :--- | :--- | :--- | :--- |\n| **A** | -0.2035 [-0.2698, -0.1371] | -0.1979 [-0.2615, -0.1286] | -0.2040 [-0.2675, -0.1374] |\n| **B** | -0.0496 [-0.2067, +0.1074] | -0.0377 [-0.1807, +0.1192] | -0.0495 [-0.2034, +0.1139] |\n| **C** | +0.0286 [-0.0258, +0.0830] | +0.0290 [-0.0255, +0.0839] | +0.0286 [-0.0261, +0.0827] |\n| **D** | -0.0184 [-0.0739, +0.0371] | -0.0182 [-0.0734, +0.0375] | -0.0188 [-0.0764, +0.0374] |\n| **E** | +0.0383 [-0.0257, +0.1023] | +0.0399 [-0.0225, +0.1046] | +0.0378 [-0.0291, +0.1030] |\n| **F** | -0.0114 [-0.0418, +0.0190] | -0.0118 [-0.0425, +0.0181] | -0.0115 [-0.0421, +0.0189] |\n\n## Summary of Findings\n\n1. **Frequentist Approach:** Uses standard normal approximations for proportions. It identifies a statistically significant overall gap favoring males, but a significant gap favoring females in Department A.\n2. **Bayesian Approach:** Uses Beta-Binomial conjugacy with a Uniform prior. Given the large sample size, the credible intervals are consistent with the frequentist results.\n3. **Computational Simulation:** Based on 5,000 bootstrap resamples. This non-parametric approach confirms the stability of the findings across models.\n\n**Key Insight:** The overall male advantage is a result of weighted averages (Simpson's Paradox). Males applied more frequently to departments with higher admission rates (A and B), while females applied more frequently to departments with lower admission rates (C-F).\n\n## Code for support\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport pandas as pd\n\ndf = pd.read_csv('./data/UCB-Admit.csv')\nprint(df.head())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    M.F Admit Dept\n0  Male   Yes    A\n1  Male   Yes    A\n2  Male   Yes    A\n3  Male   Yes    A\n4  Male   Yes    A\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(df.info())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<class 'pandas.DataFrame'>\nRangeIndex: 4526 entries, 0 to 4525\nData columns (total 3 columns):\n #   Column  Non-Null Count  Dtype\n---  ------  --------------  -----\n 0   M.F     4526 non-null   str  \n 1   Admit   4526 non-null   str  \n 2   Dept    4526 non-null   str  \ndtypes: str(3)\nmemory usage: 106.2 KB\nNone\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(df['M.F'].unique())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<StringArray>\n['Male', 'Female']\nLength: 2, dtype: str\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(df['Admit'].unique())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<StringArray>\n['Yes', 'No']\nLength: 2, dtype: str\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(df['Dept'].unique())\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n<StringArray>\n['A', 'B', 'C', 'D', 'E', 'F']\nLength: 6, dtype: str\n```\n\n\n:::\n:::\n\n\n## Part 1: Exact Binomial Confidence Intervals\n\nFirst, we calculate the exact binomial (Clopper-Pearson) confidence intervals for the probability of Admission using the Beta distribution method.\n\n\n::: {.cell}\n\n```{.python .cell-code}\nimport numpy as np\nimport scipy.stats as stats\n\n# Convert Admit to numeric: Yes=1, No=0\ndf['Admit_num'] = df['Admit'].apply(lambda x: 1 if x == 'Yes' else 0)\n\ndef frequentist_ci_prop(k, n, confidence=0.90):\n    p_hat = k / n\n    z = stats.norm.ppf(1 - (1 - confidence) / 2)\n    se = np.sqrt(p_hat * (1 - p_hat) / n)\n    return p_hat, (p_hat - z * se, p_hat + z * se)\n\ndef frequentist_ci_diff(k1, n1, k2, n2, confidence=0.90):\n    p1 = k1 / n1\n    p2 = k2 / n2\n    z = stats.norm.ppf(1 - (1 - confidence) / 2)\n    se = np.sqrt(p1 * (1 - p1) / n1 + p2 * (1 - p2) / n2)\n    diff = p1 - p2\n    return diff, (diff - z * se, diff + z * se)\n\ndef bayesian_beta(k, n, confidence=0.90, prior_a=1, prior_b=1):\n    alpha_post = prior_a + k\n    beta_post = prior_b + (n - k)\n    mean = alpha_post / (alpha_post + beta_post)\n    ci = stats.beta.ppf([(1 - confidence) / 2, 1 - (1 - confidence) / 2], alpha_post, beta_post)\n    return mean, ci\n\ndef bayesian_diff(k1, n1, k2, n2, confidence=0.90, n_samples=10000, prior_a=1, prior_b=1):\n    post1 = stats.beta.rvs(prior_a + k1, prior_b + n1 - k1, size=n_samples)\n    post2 = stats.beta.rvs(prior_a + k2, prior_b + n2 - k2, size=n_samples)\n    diffs = post1 - post2\n    mean_diff = np.mean(diffs)\n    ci = np.percentile(diffs, [(1 - confidence) / 2 * 100, (1 - (1 - confidence) / 2) * 100])\n    return mean_diff, ci\n\ndef bootstrap_stats(data_frame, n_boots=5000, confidence=0.90):\n    def get_stats(d):\n        overall = d['Admit_num'].mean()\n        male = d[d['M.F'] == 'Male']['Admit_num']\n        female = d[d['M.F'] == 'Female']['Admit_num']\n        p_m = male.mean()\n        p_f = female.mean()\n        diff = p_m - p_f\n        \n        dept_diffs = {}\n        for dept in ['A', 'B', 'C', 'D', 'E', 'F']:\n            dm = d[(d['M.F'] == 'Male') & (d['Dept'] == dept)]['Admit_num']\n            dfem = d[(d['M.F'] == 'Female') & (d['Dept'] == dept)]['Admit_num']\n            dept_diffs[dept] = dm.mean() - dfem.mean()\n            \n        return overall, p_m, p_f, diff, dept_diffs\n\n    results = []\n    for _ in range(n_boots):\n        boot_df = data_frame.sample(frac=1, replace=True)\n        results.append(get_stats(boot_df))\n    \n    # Process results\n    overalls = [r[0] for r in results]\n    p_ms = [r[1] for r in results]\n    p_fs = [r[2] for r in results]\n    diffs = [r[3] for r in results]\n    dept_diffs = {dept: [r[4][dept] for r in results] for dept in ['A', 'B', 'C', 'D', 'E', 'F']}\n    \n    alpha = (1 - confidence) / 2\n    \n    summary = {\n        'overall': (np.mean(overalls), np.percentile(overalls, [alpha*100, (1-alpha)*100])),\n        'p_m': (np.mean(p_ms), np.percentile(p_ms, [alpha*100, (1-alpha)*100])),\n        'p_f': (np.mean(p_fs), np.percentile(p_fs, [alpha*100, (1-alpha)*100])),\n        'diff': (np.mean(diffs), np.percentile(diffs, [alpha*100, (1-alpha)*100])),\n    }\n    summary['dept_diffs'] = {dept: (np.mean(dept_diffs[dept]), np.percentile(dept_diffs[dept], [alpha*100, (1-alpha)*100])) for dept in ['A', 'B', 'C', 'D', 'E', 'F']}\n    return summary\n\n# Data counts\nn_total = len(df)\nk_total = df['Admit_num'].sum()\n\ndf_m = df[df['M.F'] == 'Male']\nn_m = len(df_m)\nk_m = df_m['Admit_num'].sum()\n\ndf_f = df[df['M.F'] == 'Female']\nn_f = len(df_f)\nk_f = df_f['Admit_num'].sum()\n\n# Frequentist Results\nfreq_overall = frequentist_ci_prop(k_total, n_total)\nfreq_m = frequentist_ci_prop(k_m, n_m)\nfreq_f = frequentist_ci_prop(k_f, n_f)\nfreq_diff = frequentist_ci_diff(k_m, n_m, k_f, n_f)\n\nfreq_dept_diffs = {}\nfor dept in ['A', 'B', 'C', 'D', 'E', 'F']:\n    dm = df[(df['M.F'] == 'Male') & (df['Dept'] == dept)]\n    dfem = df[(df['M.F'] == 'Female') & (df['Dept'] == dept)]\n    freq_dept_diffs[dept] = frequentist_ci_diff(len(dm[dm['Admit_num']==1]), len(dm), \n                                               len(dfem[dfem['Admit_num']==1]), len(dfem))\n\n# Bayesian Results\nbayes_overall = bayesian_beta(k_total, n_total)\nbayes_m = bayesian_beta(k_m, n_m)\nbayes_f = bayesian_beta(k_f, n_f)\nbayes_diff_res = bayesian_diff(k_m, n_m, k_f, n_f)\n\nbayes_dept_diffs = {}\nfor dept in ['A', 'B', 'C', 'D', 'E', 'F']:\n    dm = df[(df['M.F'] == 'Male') & (df['Dept'] == dept)]\n    dfem = df[(df['M.F'] == 'Female') & (df['Dept'] == dept)]\n    bayes_dept_diffs[dept] = bayesian_diff(len(dm[dm['Admit_num']==1]), len(dm), \n                                          len(dfem[dfem['Admit_num']==1]), len(dfem))\n\n# Simulation Results\nsim_res = bootstrap_stats(df)\n\n# Print formatting\nprint(\"--- FREQUENTIST ---\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n--- FREQUENTIST ---\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Overall Admit: {freq_overall[0]:.4f} 90% CI: {freq_overall[1]}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOverall Admit: 0.3878 90% CI: (np.float64(0.3758468548858), np.float64(0.3996723673855213))\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Male Admit: {freq_m[0]:.4f} 90% CI: {freq_m[1]}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMale Admit: 0.4452 90% CI: (np.float64(0.4294291572455693), np.float64(0.46094616791236454))\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Female Admit: {freq_f[0]:.4f} 90% CI: {freq_f[1]}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFemale Admit: 0.3035 90% CI: (np.float64(0.2858872970784858), np.float64(0.3211971715863643))\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Difference (M-F): {freq_diff[0]:.4f} 90% CI: {freq_diff[1]}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDifference (M-F): 0.1416 90% CI: (np.float64(0.11798053230797384), np.float64(0.16531032418510988))\n```\n\n\n:::\n\n```{.python .cell-code}\nfor dept, res in freq_dept_diffs.items():\n    print(f\"Dept {dept} Diff: {res[0]:.4f} 90% CI: {res[1]}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDept A Diff: -0.2035 90% CI: (np.float64(-0.26983065836437714), np.float64(-0.1371053685716498))\nDept B Diff: -0.0496 90% CI: (np.float64(-0.20672494857181703), np.float64(0.10743923428610261))\nDept C Diff: 0.0286 90% CI: (np.float64(-0.02584881896001337), np.float64(0.08302873853453666))\nDept D Diff: -0.0184 90% CI: (np.float64(-0.07386425391360701), np.float64(0.03706809084406266))\nDept E Diff: 0.0383 90% CI: (np.float64(-0.025673244530764167), np.float64(0.10227556524802836))\nDept F Diff: -0.0114 90% CI: (np.float64(-0.04175948097266083), np.float64(0.01895948411748796))\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"\\n--- BAYESIAN ---\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- BAYESIAN ---\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Overall Admit: {bayes_overall[0]:.4f} 90% CrI: {bayes_overall[1]}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOverall Admit: 0.3878 90% CrI: [0.37592815 0.39974658]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Male Admit: {bayes_m[0]:.4f} 90% CrI: {bayes_m[1]}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMale Admit: 0.4452 90% CrI: [0.42950123 0.46100177]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Female Admit: {bayes_f[0]:.4f} 90% CrI: {bayes_f[1]}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFemale Admit: 0.3038 90% CrI: [0.28623373 0.32152152]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Difference (M-F): {bayes_diff_res[0]:.4f} 90% CrI: {bayes_diff_res[1]}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDifference (M-F): 0.1412 90% CrI: [0.11819391 0.1646385 ]\n```\n\n\n:::\n\n```{.python .cell-code}\nfor dept, res in bayes_dept_diffs.items():\n    print(f\"Dept {dept} Diff: {res[0]:.4f} 90% CrI: {res[1]}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDept A Diff: -0.1978 90% CrI: [-0.26185713 -0.12932448]\nDept B Diff: -0.0357 90% CrI: [-0.17912809  0.12065017]\nDept C Diff: 0.0289 90% CrI: [-0.02559814  0.0829712 ]\nDept D Diff: -0.0180 90% CrI: [-0.07366351  0.03707448]\nDept E Diff: 0.0391 90% CrI: [-0.02448831  0.10466703]\nDept F Diff: -0.0115 90% CrI: [-0.04283984  0.01941818]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(\"\\n--- COMPUTATIONAL SIMULATION ---\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n--- COMPUTATIONAL SIMULATION ---\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Overall Admit: {sim_res['overall'][0]:.4f} 90% CI: {sim_res['overall'][1]}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOverall Admit: 0.3877 90% CI: [0.37604949 0.39969068]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Male Admit: {sim_res['p_m'][0]:.4f} 90% CI: {sim_res['p_m'][1]}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMale Admit: 0.4451 90% CI: [0.42924671 0.4606289 ]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Female Admit: {sim_res['p_f'][0]:.4f} 90% CI: {sim_res['p_f'][1]}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nFemale Admit: 0.3036 90% CI: [0.28579084 0.32152457]\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Difference (M-F): {sim_res['diff'][0]:.4f} 90% CI: {sim_res['diff'][1]}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDifference (M-F): 0.1415 90% CI: [0.11737895 0.16528944]\n```\n\n\n:::\n\n```{.python .cell-code}\nfor dept, res in sim_res['dept_diffs'].items():\n    print(f\"Dept {dept} Diff: {res[0]:.4f} 90% CI: {res[1]}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDept A Diff: -0.2033 90% CI: [-0.2708652  -0.13347945]\nDept B Diff: -0.0482 90% CI: [-0.20402083  0.11603879]\nDept C Diff: 0.0283 90% CI: [-0.02540717  0.08298603]\nDept D Diff: -0.0181 90% CI: [-0.07454795  0.03755378]\nDept E Diff: 0.0382 90% CI: [-0.02309469  0.10177894]\nDept F Diff: -0.0115 90% CI: [-0.04130332  0.01939095]\n```\n\n\n:::\n:::\n\n\n### Interpretation of Exact Intervals\n\nOverall, Males had an admission rate of **44.52%** (95% CI: 42.63% - 46.42%), while Females had an admission rate of **30.35%** (95% CI: 28.26% - 32.52%). \n\n---\n\n## Part 2: Normal Approximation (Wald Method) and Differences\n\nNext, we re-analyze the data utilizing the normal approximation (Wald method) for binomial confidence intervals at 95%. This allows us to easily calculate the confidence intervals for the *differences* in probability of admission (Male minus Female).\n\n\n::: {.cell tbl-cap='Normal Approximation Confidence Intervals and Differences'}\n\n```{.python .cell-code}\nimport numpy as np\nfrom scipy.stats import norm\n\nz = norm.ppf(0.975) # 1.96 for 95% CI\n\ndef wald_ci(k, n):\n    if n == 0: return np.nan, np.nan, np.nan\n    p = k / n\n    se = np.sqrt(p * (1 - p) / n)\n    return p, p - z * se, p + z * se\n\ndef wald_diff_ci(k1, n1, k2, n2):\n    if n1 == 0 or n2 == 0: return np.nan, np.nan, np.nan\n    p1 = k1 / n1\n    p2 = k2 / n2\n    diff = p1 - p2\n    se = np.sqrt(p1 * (1 - p1) / n1 + p2 * (1 - p2) / n2)\n    return diff, diff - z * se, diff + z * se\n\n# Overall Stats Calculation\npm, pm_low, pm_high = wald_ci(k_m, n_m)\npf, pf_low, pf_high = wald_ci(k_f, n_f)\ndiff_o, diff_o_low, diff_o_high = wald_diff_ci(k_m, n_m, k_f, n_f)\n\nprint(\"--- Overall Admission Differences ---\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n--- Overall Admission Differences ---\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Overall Males: p={pm:.4f}, CI=({pm_low:.4f}, {pm_high:.4f})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOverall Males: p=0.4452, CI=(0.4264, 0.4640)\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Overall Females: p={pf:.4f}, CI=({pf_low:.4f}, {pf_high:.4f})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOverall Females: p=0.3035, CI=(0.2825, 0.3246)\n```\n\n\n:::\n\n```{.python .cell-code}\nprint(f\"Overall Diff (M-F): diff={diff_o:.4f}, CI=({diff_o_low:.4f}, {diff_o_high:.4f})\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOverall Diff (M-F): diff=0.1416, CI=(0.1134, 0.1698)\n```\n\n\n:::\n\n```{.python .cell-code}\n# Department Level Calculation\ndept_results = []\nfor dept in sorted(df['Dept'].unique()):\n    m_sub = df[(df['M.F'] == 'Male') & (df['Dept'] == dept)]\n    f_sub = df[(df['M.F'] == 'Female') & (df['Dept'] == dept)]\n    \n    k_m_dept = (m_sub['Admit'] == 'Yes').sum()\n    n_m_dept = len(m_sub)\n    k_f_dept = (f_sub['Admit'] == 'Yes').sum()\n    n_f_dept = len(f_sub)\n    \n    p_m, pm_l, pm_h = wald_ci(k_m_dept, n_m_dept)\n    p_f, pf_l, pf_h = wald_ci(k_f_dept, n_f_dept)\n    diff, diff_l, diff_h = wald_diff_ci(k_m_dept, n_m_dept, k_f_dept, n_f_dept)\n    \n    dept_results.append({\n        'Dept': dept,\n        'Male_p': p_m, 'Male_CI_L': pm_l, 'Male_CI_U': pm_h,\n        'Female_p': p_f, 'Female_CI_L': pf_l, 'Female_CI_U': pf_h,\n        'Diff': diff, 'Diff_CI_L': diff_l, 'Diff_CI_U': diff_h\n    })\n\nres_diff_df = pd.DataFrame(dept_results)\nres_diff_df.style.format({\n    'Male_p': '{:.2%}', 'Male_CI_L': '{:.2%}', 'Male_CI_U': '{:.2%}',\n    'Female_p': '{:.2%}', 'Female_CI_L': '{:.2%}', 'Female_CI_U': '{:.2%}',\n    'Diff': '{:.2%}', 'Diff_CI_L': '{:.2%}', 'Diff_CI_U': '{:.2%}'\n})\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<style type=\"text/css\">\n</style>\n<table id=\"T_40082\">\n  <thead>\n    <tr>\n      <th class=\"blank level0\" >&nbsp;</th>\n      <th id=\"T_40082_level0_col0\" class=\"col_heading level0 col0\" >Dept</th>\n      <th id=\"T_40082_level0_col1\" class=\"col_heading level0 col1\" >Male_p</th>\n      <th id=\"T_40082_level0_col2\" class=\"col_heading level0 col2\" >Male_CI_L</th>\n      <th id=\"T_40082_level0_col3\" class=\"col_heading level0 col3\" >Male_CI_U</th>\n      <th id=\"T_40082_level0_col4\" class=\"col_heading level0 col4\" >Female_p</th>\n      <th id=\"T_40082_level0_col5\" class=\"col_heading level0 col5\" >Female_CI_L</th>\n      <th id=\"T_40082_level0_col6\" class=\"col_heading level0 col6\" >Female_CI_U</th>\n      <th id=\"T_40082_level0_col7\" class=\"col_heading level0 col7\" >Diff</th>\n      <th id=\"T_40082_level0_col8\" class=\"col_heading level0 col8\" >Diff_CI_L</th>\n      <th id=\"T_40082_level0_col9\" class=\"col_heading level0 col9\" >Diff_CI_U</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th id=\"T_40082_level0_row0\" class=\"row_heading level0 row0\" >0</th>\n      <td id=\"T_40082_row0_col0\" class=\"data row0 col0\" >A</td>\n      <td id=\"T_40082_row0_col1\" class=\"data row0 col1\" >62.06%</td>\n      <td id=\"T_40082_row0_col2\" class=\"data row0 col2\" >58.75%</td>\n      <td id=\"T_40082_row0_col3\" class=\"data row0 col3\" >65.37%</td>\n      <td id=\"T_40082_row0_col4\" class=\"data row0 col4\" >82.41%</td>\n      <td id=\"T_40082_row0_col5\" class=\"data row0 col5\" >75.23%</td>\n      <td id=\"T_40082_row0_col6\" class=\"data row0 col6\" >89.59%</td>\n      <td id=\"T_40082_row0_col7\" class=\"data row0 col7\" >-20.35%</td>\n      <td id=\"T_40082_row0_col8\" class=\"data row0 col8\" >-28.25%</td>\n      <td id=\"T_40082_row0_col9\" class=\"data row0 col9\" >-12.44%</td>\n    </tr>\n    <tr>\n      <th id=\"T_40082_level0_row1\" class=\"row_heading level0 row1\" >1</th>\n      <td id=\"T_40082_row1_col0\" class=\"data row1 col0\" >B</td>\n      <td id=\"T_40082_row1_col1\" class=\"data row1 col1\" >63.04%</td>\n      <td id=\"T_40082_row1_col2\" class=\"data row1 col2\" >59.04%</td>\n      <td id=\"T_40082_row1_col3\" class=\"data row1 col3\" >67.03%</td>\n      <td id=\"T_40082_row1_col4\" class=\"data row1 col4\" >68.00%</td>\n      <td id=\"T_40082_row1_col5\" class=\"data row1 col5\" >49.71%</td>\n      <td id=\"T_40082_row1_col6\" class=\"data row1 col6\" >86.29%</td>\n      <td id=\"T_40082_row1_col7\" class=\"data row1 col7\" >-4.96%</td>\n      <td id=\"T_40082_row1_col8\" class=\"data row1 col8\" >-23.68%</td>\n      <td id=\"T_40082_row1_col9\" class=\"data row1 col9\" >13.75%</td>\n    </tr>\n    <tr>\n      <th id=\"T_40082_level0_row2\" class=\"row_heading level0 row2\" >2</th>\n      <td id=\"T_40082_row2_col0\" class=\"data row2 col0\" >C</td>\n      <td id=\"T_40082_row2_col1\" class=\"data row2 col1\" >36.92%</td>\n      <td id=\"T_40082_row2_col2\" class=\"data row2 col2\" >31.68%</td>\n      <td id=\"T_40082_row2_col3\" class=\"data row2 col3\" >42.17%</td>\n      <td id=\"T_40082_row2_col4\" class=\"data row2 col4\" >34.06%</td>\n      <td id=\"T_40082_row2_col5\" class=\"data row2 col5\" >30.25%</td>\n      <td id=\"T_40082_row2_col6\" class=\"data row2 col6\" >37.88%</td>\n      <td id=\"T_40082_row2_col7\" class=\"data row2 col7\" >2.86%</td>\n      <td id=\"T_40082_row2_col8\" class=\"data row2 col8\" >-3.63%</td>\n      <td id=\"T_40082_row2_col9\" class=\"data row2 col9\" >9.35%</td>\n    </tr>\n    <tr>\n      <th id=\"T_40082_level0_row3\" class=\"row_heading level0 row3\" >3</th>\n      <td id=\"T_40082_row3_col0\" class=\"data row3 col0\" >D</td>\n      <td id=\"T_40082_row3_col1\" class=\"data row3 col1\" >33.09%</td>\n      <td id=\"T_40082_row3_col2\" class=\"data row3 col2\" >28.58%</td>\n      <td id=\"T_40082_row3_col3\" class=\"data row3 col3\" >37.61%</td>\n      <td id=\"T_40082_row3_col4\" class=\"data row3 col4\" >34.93%</td>\n      <td id=\"T_40082_row3_col5\" class=\"data row3 col5\" >30.11%</td>\n      <td id=\"T_40082_row3_col6\" class=\"data row3 col6\" >39.76%</td>\n      <td id=\"T_40082_row3_col7\" class=\"data row3 col7\" >-1.84%</td>\n      <td id=\"T_40082_row3_col8\" class=\"data row3 col8\" >-8.45%</td>\n      <td id=\"T_40082_row3_col9\" class=\"data row3 col9\" >4.77%</td>\n    </tr>\n    <tr>\n      <th id=\"T_40082_level0_row4\" class=\"row_heading level0 row4\" >4</th>\n      <td id=\"T_40082_row4_col0\" class=\"data row4 col0\" >E</td>\n      <td id=\"T_40082_row4_col1\" class=\"data row4 col1\" >27.75%</td>\n      <td id=\"T_40082_row4_col2\" class=\"data row4 col2\" >21.40%</td>\n      <td id=\"T_40082_row4_col3\" class=\"data row4 col3\" >34.10%</td>\n      <td id=\"T_40082_row4_col4\" class=\"data row4 col4\" >23.92%</td>\n      <td id=\"T_40082_row4_col5\" class=\"data row4 col5\" >19.70%</td>\n      <td id=\"T_40082_row4_col6\" class=\"data row4 col6\" >28.14%</td>\n      <td id=\"T_40082_row4_col7\" class=\"data row4 col7\" >3.83%</td>\n      <td id=\"T_40082_row4_col8\" class=\"data row4 col8\" >-3.79%</td>\n      <td id=\"T_40082_row4_col9\" class=\"data row4 col9\" >11.45%</td>\n    </tr>\n    <tr>\n      <th id=\"T_40082_level0_row5\" class=\"row_heading level0 row5\" >5</th>\n      <td id=\"T_40082_row5_col0\" class=\"data row5 col0\" >F</td>\n      <td id=\"T_40082_row5_col1\" class=\"data row5 col1\" >5.90%</td>\n      <td id=\"T_40082_row5_col2\" class=\"data row5 col2\" >3.51%</td>\n      <td id=\"T_40082_row5_col3\" class=\"data row5 col3\" >8.29%</td>\n      <td id=\"T_40082_row5_col4\" class=\"data row5 col4\" >7.04%</td>\n      <td id=\"T_40082_row5_col5\" class=\"data row5 col5\" >4.32%</td>\n      <td id=\"T_40082_row5_col6\" class=\"data row5 col6\" >9.75%</td>\n      <td id=\"T_40082_row5_col7\" class=\"data row5 col7\" >-1.14%</td>\n      <td id=\"T_40082_row5_col8\" class=\"data row5 col8\" >-4.76%</td>\n      <td id=\"T_40082_row5_col9\" class=\"data row5 col9\" >2.48%</td>\n    </tr>\n  </tbody>\n</table>\n```\n\n:::\n:::\n\n\n### Analysis of the Differences & Simpson's Paradox\n\n1. **Overall:** Males had a higher probability of being admitted compared to Females. Based on the normal approximation, the overall difference in probability is statistically significant because the 95% CI for the difference (+11.34% to +16.98%) does not cross zero.\n2. **By Department (Simpson's Paradox):** When we re-examine the data by looking at each department separately, the trend reverses or disappears:\n   * **Department A:** Females were admitted at a significantly higher rate than Males (the 95% CI for the Male-Female difference is entirely negative: -28.25% to -12.44%).\n   * **Departments B, C, D, E, F:** The 95% confidence intervals for the differences all cross zero, meaning there is **no statistically significant difference** between Male and Female admission probabilities in any of these individual departments. \n\nThis illustrates a classic example of **Simpson's Paradox**: a trend appears in different groups of data but disappears or reverses when these groups are combined.",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}